# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-08 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
