# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 22:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20170709_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimage',
            name='post',
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
